/*
 * gplugin.h
 *
 */

/* OPDKのバージョン */
#ifndef GPDK_VER
#define GPDK_VER 0
#elif GPDK_VER > 0
#error "Incorrect GPDK version."
#endif

typedef enum {
	GENERAL_PLUGIN_EVENT_INIT = 0,
	GENERAL_PLUGIN_EVENT_QUIT,
	GENERAL_PLUGIN_EVENT_TRACK_CHANGE,
	GENERAL_PLUGIN_EVENT_STATUS_CHANGE,
	GENERAL_PLUGIN_EVENT_CONFIG_CHANGE,
	GENERAL_PLUGIN_EVENT_INIT2,
	GENERAL_PLUGIN_EVENT_INIT0
} GENERAL_PLUGIN_EVENT;

typedef struct GENERAL_PLUGIN_HOOK_WNDPROC_TAG {
	HWND hWnd;
	UINT msg;
	WPARAM wp;
	LPARAM lp;
	LRESULT lMsgResult;
} GENERAL_PLUGIN_HOOK_WNDPROC;
typedef GENERAL_PLUGIN_HOOK_WNDPROC *LPGENERAL_PLUGIN_HOOK_WNDPROC;

typedef struct GENERAL_PLUGIN_INFO_TAG {
	int nGPDKVer;

	/* v0 */
	BOOL (CALLBACK *HookWndProc)(LPGENERAL_PLUGIN_HOOK_WNDPROC pMsg);

	BOOL (CALLBACK *OnEvent)(HWND hWnd, GENERAL_PLUGIN_EVENT eCode);

} GENERAL_PLUGIN_INFO;

/* インターフェースの宣言 */
typedef GENERAL_PLUGIN_INFO *(CALLBACK *GetGPluginInfoFunc)();
